services:
  etcd:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - service-registry-ptrn-etcd-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - etcd
    environment:
      - ETCD_ENDPOINT=http://etcd:2379
    networks:
      - service-registry-ptrn-etcd-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - etcd
    environment:
      - ETCD_ENDPOINT=http://etcd:2379
    networks:
      - service-registry-ptrn-etcd-network

networks:
  service-registry-ptrn-etcd-network:
    driver: bridge
    external: true
