apiVersion: v1
kind: Namespace
metadata:
  name: svc-time-echo-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-time-echo
  namespace: svc-time-echo-ns
  labels:
    app: svc-time-echo
spec:
  selector:
    matchLabels:
      app: svc-time-echo
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: svc-time-echo-ns
      labels:
        app: svc-time-echo
    spec:
      containers:
        - name: svc-time-echo
          image: svc-time-echo:0.0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 8891
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8891
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            exec:
              command:
              - busybox
              - cat
              - /tmp/healthy
            initialDelaySeconds: 20
            periodSeconds: 15