apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-time-echo
  name: svc-time-echo
  namespace: svc-time-echo-ns
spec:
  ports:
  - port: 8891
    protocol: TCP
    targetPort: 8891
  selector:
    app: svc-time-echo
  type: ClusterIP
