version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    networks:
      - mynetwork

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - mynetwork

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
