apiVersion: v1
kind: Service
metadata:
  name: tcpechosrv-example
  labels:
    app: tcpechosrv
spec:
  ports:
  - port: 10500
    protocol: TCP
    targetPort: 10500
  selector:
    app: tcpechosrv
  type: ClusterIP
